# Generated by Django 3.2.9 on 2023-02-20 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DashboardApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='stock',
            field=models.IntegerField(verbose_name='Stock'),
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio')),
                ('cant', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Subtotal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.productmodel', verbose_name='Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ['id'],
            },
        ),
    ]
