# Generated by Django 3.2.9 on 2023-02-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0002_auto_20230220_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d')),
                ('address', models.CharField(max_length=100, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Business',
                'ordering': ['id'],
            },
        ),
    ]
