# Generated by Django 3.2.9 on 2023-03-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0003_businessmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Offer'),
        ),
    ]
