# Generated by Django 3.2.9 on 2023-03-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0004_productmodel_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
